Align files
giantswarm/keda-app pull request #25
Opened 2022-03-31 11:51 UTC by architectbot

This PR is generated by https://github.com/giantswarm/github, it will be merged automatically once all requirements are met

2022-04-04 09:04 UTC, ubergesundheit commented
@mleisa check changes I did in https://github.com/giantswarm/velero-app/pull/43
please do the same here (add a new `_helpers.tpl` and supply common and selector labels from there)

2022-04-08 10:43 UTC, mleisa commented on helm/keda/templates/12-keda-deployment.yaml
> -    name: {{ .Values.operator.name }}
Was this "name" an additional label or metadata that was indented wrong?

2022-04-08 11:05 UTC, ubergesundheit commented on helm/keda/templates/12-keda-deployment.yaml
> -    name: {{ .Values.operator.name }}
I think this was a label, the `name` is already there in line 4 above.

2022-04-08 11:38 UTC, ubergesundheit requested changes
I don't see the `"labels.selector"` used except in the `"labels.common"` helper.

The idea behind defining a selector labels helper is to have these aligned throughout the resources.

This also means it should be used in places where kubernetes components use these labels as means for matching resources (Deployment/Pod for example)

Also, please check all other places where labels are used (exclude CRDs for now)

2022-04-08 15:13 UTC, ubergesundheit commented on helm/keda/templates/12-keda-deployment.yaml
>      app: {{ .Values.operator.name }}
```suggestion
```

2022-04-08 15:41 UTC, ubergesundheit commented on helm/keda/templates/22-metrics-deployment.yaml
>      app: {{ .Values.operator.name }}-metrics-apiserver
```suggestion
```

2022-04-14 14:12 UTC, merged